Repository gopulse/pulse, pull requests merged in 2023-04, with the labels that each got.

#2 Add .circleci/config.yml
  .circleci/config.yml
Labels: :broom: Updates, :+1: Accepted PR

#11 Bug: Handle slash suffix in route path
  .github/pull_request_template.md
  group.go
  router.go
Labels: :+1: Accepted PR

#15 Updates: Enhancements in framework
  README.md
  constants/methods.go
  context.go
  route.go
  utils/strings.go
  utils/strings_test.go
Labels: :page_facing_up: Documentation, :broom: Updates

#17 ISSUE-16: Enhancements in Pulse logic
  app.go
  context.go
  context_test.go
  go.mod
  route.go
  router.go
  router_test.go
Labels: :stop_sign: High Priority, :skull: Breaking Change

#18 Updates: Cleanup the project
  utils/json.go
  utils/json_test.go
Labels: :broom: Updates

#21 Updates: Improve test coverage env
  context.go
  context_test.go
  middleware_test.go
Labels: :broom: Updates

#22 chore: fix code blocks formatting in readme
  README.md
Labels: :page_facing_up: Documentation

#24 Implement validator package
  go.mod
  go.sum
Labels: :page_facing_up: Documentation, :pencil2: Feature
